### ISSUE TITLE
biblioteca/arquivo não existe

### ISSUE THREAD

**Issue by danroxha** [DavidGomesh/cryptography-with-geometric-transpositions#1]
https://github.com/DavidGomesh/cryptography-with-geometric-transpositions/blob/c43f1d2dc43d9f698496ed35612663d4ecdef8bc/main.c#L5

Arquivo ***geometric-transpositions/columnar-with-numeric-key.h*** não existe e está sendo chamado no arquivo main.c

**Comment by DavidGomesh** [comment]
Esse arquivo foi renomeado para _**linear-with-numeric-key.h**_. E o arquivo **_main.c_** foi utilizado apenas para testes durante o desenvolvimento.

O programa contendo todas as criptografias e decriptografias já está sendo implementado, logo estará disponível.

Muito obrigado pelo alerta! 😄👍🏻
